### PR TITLE
Muth0mi convert to kotlin

### PR DESCRIPTION
**Pull request by jumaallan**
cleanup edits
updated PR conflicts

### CODE REVIEW

**Comment by jumaallan** [comment]
@muth0mi - merge this PR, so that we can re-merge your PR. Also, after merge, I will open an issue to fix androidX bug that's popping up

**Comment by muth0mi** [comment]
Done.

**Comment by jumaallan** [comment]
@muth0mi thanks - merged your changes too

**Comment by jumaallan** [comment]
See this issue - https://github.com/jumaallan/android-mpesa-api/issues/41

@muth0mi you can do a PR to fix this too

**Comment by muth0mi** [comment]
@jumaallan thanks. Let me check it out.

**Comment by muth0mi** [comment]
Assign it to me.

**Pull request merged**
